name: logic-gate-calculator
version: 0.1.0.0
synopsis: Logic gate calculator
description: Single-digit LED calculator using logic gates
category: Simulation
author: Bretton Chen
maintainer: Bretton Chen
copyright: (c) 2018 Bretton Chen
license: MIT
github: qsctr/logic-gate-calculator
extra-source-files:
  - README.md
dependencies:
  - base >= 4.7 && < 5
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
executable:
  source-dirs: src
  main: Main.hs
